(function(g){var window=this;var r1=function(a){var b={format:a.o,languageCode:a.l,languageName:a.A,displayName:g.Wu(a),kind:a.B,name:a.C,id:a.Ea,is_servable:a.R,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},s1=function(a){return a.g?a.g.languageCode:a.l},Hka=function(a,b){var c=new g.Vu;
c.l=a.l;c.A=a.A;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},t1=function(a){return(a=g.W(a.app,void 0))?a.F?a.F.A:0:0},u1=function(a){if(!Ika.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Jka,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},v1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.DD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.o=f;this.l=k},w1=function(a,b,c,d,e){g.DD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},y1=function(a){a=void 0===a?{}:a;
var b="_"+x1++;return new w1(0,0x8000000000000,0,b,a)},A1=function(a,b,c,d,e,f){var k={};
g.Ka(k,b);g.Ka(k,a.params);g.Ka(k,c);var l={};g.Ka(l,b.Pa);a.params.Pa&&g.Ka(l,a.params.Pa);g.Ka(l,c.Pa);k.Pa=l;g.Q.call(this,{D:"div",I:"caption-window",O:{id:"caption-window-"+a.id,dir:1==k.Ui?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{D:"span",I:"captions-text"}]});this.A=[];this.N=!1;this.F=a;this.C=[];this.G=[];this.Ha=e;this.za=f;this.B=null;this.Z=.96*e;this.na=.96*f;this.l=k;this.wa=c;this.o=this.g["captions-text"];this.pa=null!=this.o.style["box-decoration-break"]||
null!=this.o.style["-webkit-box-decoration-break"];this.R=d/360*16;this.type=0;this.ka=this.R*z1(l);a=new g.Ps(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.eG,this);a.subscribe("dragmove",this.dG,this);a.subscribe("dragend",this.cG,this);this.ia=this.da=0;a="";this.l.windowOpacity&&(a=u1(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":Kka[this.l.textAlign]};this.pa&&(b["border-radius"]=
a?this.ka/8+"px":"");g.Rh(this.element,b);switch(this.l.hf){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},z1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},B1=function(a,b){var c={},d=b.background?b.background:a.l.Pa.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.Pa.backgroundOpacity;d=u1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.pa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.R*z1(b)+"px";d=1;e=b.color||a.l.Pa.color;if(b.color||null!=b.textOpacity)e=u1(e),d=null==b.textOpacity?a.l.Pa.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Ct&&(k=e=b.Ct);var l=a.R/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=u;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Ir()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.Pa.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ke&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.Ap&&(c.visibility="hidden");return c},C1=function(a,b,c){a.N=a.N||!!c;
var d={};g.Ka(d,a.l.Pa);g.Ka(d,c||b.l);g.Ka(d,a.wa.Pa);c=a.C[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Ap==!!c.Ap&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.C.length;e++)if(g.nc(d,a.C[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.ce("SPAN");g.Rh(f,B1(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.C.length=e}else a.G.length=0,a.C.length=0,f=g.ce("SPAN"),g.Rh(f,B1(a,d)),a.o.appendChild(f);a.B&&a.B.parentNode!=f&&(g.ie(a.B),
f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.A.length||!b.o){if(0<e||0!=a.A.length){var m=g.ce("BR");f.appendChild(m)}f.appendChild(g.de("\u00a0"));a.B=g.de("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.de(l):l,m))}a.C.push(d);a.G.push(f);a.A.push(b)},D1=function(){},F1=function(){this.A=this.l=this.mode=this.o=0;
this.B=new E1(this);this.C=new E1(this);this.g=[];this.clear()},Lka=function(a,b,c){if(255==a&&255==b||!a&&!b)return{jl:a,
kl:b,result:0};a=G1[a];b=G1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{jl:a,kl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{jl:a,kl:b,result:2};return{jl:a,kl:b,result:3}},Mka=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,H1(a.B,b,c,d))},Nka=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Mka(a,d.wt,d.xt,b):1==d.type&&a.o&496&&H1(a.C,d.wt,d.xt,b)}a.g.length=0},I1=function(){this.g=0},J1=function(){this.l=this.o=this.g=0},K1=function(){this.timestamp=this.Ld=0},L1=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new K1}this.g=this.l=this.row=0;this.style=new I1;this.B=a;this.A=0},M1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var u=a.o[m][q];
if(0!=u.Ld){0==c&&(c=m,d=q);n=String.fromCharCode(u.Ld);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Ld||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],u=q.Ld,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=q.timestamp,x<=e&&(e=x),l+=n,q.reset()),32==m||0==u)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Ska=function(a,b){switch(a){case 0:return Oka[(b&127)-32];
case 1:return Pka[b&15];case 2:return Qka[b&31];case 3:return Rka[b&31]}return 0},N1=function(a){return a.o[a.row][a.l]},O1=function(a,b,c){2<=b&&1<a.l&&(--a.l,N1(a).Ld=0);
var d=N1(a);d.timestamp=a.B.l+0;d.Ld=Ska(b,c);32>a.l&&a.l++},P1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].xl(a.o[c+e][f])},Q1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},R1=function(a){a.row=0<a.g?a.g:1;
a.l=1;Q1(a,0,15)},S1=function(a){this.A=a;
this.B=0;this.style=new I1;this.C=new L1(a);this.F=new L1(a);this.G=new L1(a);this.l=this.C;this.o=this.F;this.g=this.l},T1=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:M1(d,c),R1(a.l),R1(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(M1(d,c),Q1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},U1=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},V1=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.A.mode=1<<a.g.A},E1=function(a){this.l=a;
this.g=new J1;this.B=0;this.o=new S1(a);this.C=new S1(a);this.A=this.o},H1=function(a,b,c,d){a.g.update();
b=Lka(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.jl;c=b.kl;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&O1(a,0,b),c&96&&O1(a,0,c),0!=b&&0!=c&&3==a.style.g&&M1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;P1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));Q1(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:O1(b.g,0,32);break a;case 48:57==c?(b=b.g,N1(b).Ld=0,32>b.l&&b.l++):O1(b.g,1,c&15)}break;case 2:c&32&&O1(b.g,2,c&31);break;case 3:c&32&&O1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:U1(b);break;case 33:b=
b.g;1<b.l&&(--b.l,N1(b).Ld=0);break;case 36:b=b.g;d=N1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:T1(b,2,d);break;case 38:T1(b,3,d);break;case 39:T1(b,4,d);break;case 40:O1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.G;d.g=15;d.style.set(4);R1(d);V1(b);break;case 43:V1(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:M1(a,d)}Q1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;M1(a,d);P1(a,b,b+1,a.g-1);Q1(a,a.row,1)}break;case 46:Q1(b.o,0,15);break;case 47:M1(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;U1(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},W1=function(a){g.H.apply(this,arguments)},X1=function(a){W1.call(this);
this.l=a;this.g=null},Z1=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Up("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Y1(d,e,k,b,f,a.firstChild,{},c)},Y1=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.ke=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");$1.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new v1(a,b,c,d,n.nodeValue,e||0<m,g.jc(k)?void 0:k));else{var q={};g.Ka(q,k);Y1(a,b,c,d,e||0<m,n,q,l)}}},a2=function(){W1.call(this);
this.l={};this.g=null},b2=function(a){W1.call(this);
this.A={};this.H={};this.J={};this.B="_"+x1++;this.C=a;this.G={};this.l=this.g=null;this.F=!0},c2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},d2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},e2=function(a,b){var c=c2(a,b);
if(void 0!=c)return c},f2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return $1.test(c),c},g2=function(a,b){var c={},d=b.getAttribute("ws");
g.Ka(c,d?a.J[d]:a.C);d=e2(b,"mh");null!=d&&(c.Zp=d);d=e2(b,"ju");null!=d&&(c.textAlign=d);d=e2(b,"pd");null!=d&&(c.Ui=d);d=f2(b,"wfc");null!=d&&(c.windowColor=d);d=c2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},h2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ka(c,a.H[d]);d=e2(b,"ap");null!=d&&(c.hf=d);d=c2(b,"cc");null!=d&&(c.Eo=d);d=c2(b,"ah");null!=d&&(c.ne=d);d=c2(b,"rc");null!=d&&(c.Cn=d);d=c2(b,"av");null!=d&&(c.Rf=d);return c},i2=function(a,b,c,d){var e={};
g.Ka(e,h2(a,b));g.Ka(e,g2(a,b));d?g.nc(e,a.C)?(d=a.B,e=a.C):d="_"+x1++:d=b.getAttribute("id")||"_"+x1++;a=c2(b,"t")+c;b=c2(b,"d")||0x8000000000000;return new w1(a,b,0,d,e)},j2=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},k2=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},l2=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},m2=function(a,b){W1.call(this);
this.l=a;this.track="CC3"==b.A?4:0;this.g=new F1;this.g.o=1<<this.track},o2=function(a){if(g.v(a))return!1;
a=new j2(a,8,0);return n2(a)},n2=function(a){if(!(a.g<a.l.byteLength)||1380139777!=l2(a))return!1;
a.version=k2(a);if(1<a.version)return!1;k2(a);k2(a);k2(a);return!0},Tka=function(){this.l=[];
this.g=[]},p2=function(a,b){return b?a.g.concat(a.l):a.g},q2=function(a,b){switch(b.B){case "asr":var c=a.l;
g.Pa(c,(0,g.A)(b.J,b))||c.push(b);break;default:c=a.g,g.Pa(c,(0,g.A)(b.J,b))||c.push(b)}},r2=function(){W1.call(this)},s2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.ke=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new v1(b,c,d,e.id,q.nodeValue,f||0<n,g.jc(l)?void 0:l);m.push(q);var u=e;g.I(u,q);u.l.push(q)}else u={},g.Ka(u,l),s2(a,b,c,d,e,!0,q,u,m)}},t2=function(a){var b=0;
a=g.p(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},u2=function(a,b,c,d){d=Object.assign({Zp:0},d);
return new w1(a,b,c,"_"+x1++,d)},v2=function(a){g.H.call(this);
this.Xu=!!a;this.l=new Tka;this.C=[];this.g=null},w2=function(a){var b={};
if(a=s1(a))b.lang=a,Uka.test(a)&&(b.Ui=1);return b},Vka=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);if(1718909296==f.getUint32(4)&&(f=g.Pw(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),!o2(b)&&(b=g.Ce(new window.Uint8Array(b)),!b)))return[]}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new r2),a.g.o(b,d);b=g.Up(b);if(!b||!b.firstChild)return[];if(!a.g)if("timedtext"==b.firstChild.tagName)3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new b2(w2(c)):a.g=new a2,g.I(a,a.g);else try{return a.g=new X1(w2(c)),g.I(a,
a.g),a.g.o(b,d)}catch(k){return g.N(k),a.g=null,[]}return a.g.o(b,d)}try{if(o2(b))return a.g||(a.g=new m2(e,c)),a.g.o(b,d)}catch(k){g.N(k),a.g=null}return[]},x2=function(a){v2.call(this,a.rl);
this.A=void 0;this.o=null;this.C=a.captionTranslationLanguages},y2=function(){this.Ua=[]},z2=function(a,b,c,d,e,f){g.H.call(this);
this.N=a;this.o=b;this.C=new y2;this.g=null;this.H=d;this.R=f;this.l=this.A=null;this.G=c;this.F=e||!1;this.J=new g.M(this.zv,1E3,this);g.I(this,this.J);this.B=new g.Ls(this);g.I(this,this.B);this.B.M(b,"seekto",this.Aw);this.Aw(b.getCurrentTime());this.zv()},A2=function(a,b){b-=t1(a.o);
var c=a.g;a.g=g.Ma(a.G.sf(b).g);c!=a.g&&a.R&&a.R()},B2=function(a,b){var c=g.ky(b,a.N,{}).yb(),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.l=g.Ur(c,d,3,100).then((0,g.A)(a.qK,a));a.A=b;c=a.C;d=a.A.g[0].oa;var e=g.jb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.Wa(c.Ua,e),g.Wa(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.eb(c.Ua,e,0,d),g.eb(c.Ua,e+1,0,d)))},C2=function(a,b){v2.call(this);
this.o=a;this.L=b;this.A=null;this.B=!1},Wka=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.Ly(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.lv(d.info.mimeType)&&("386"!=c||!g.R(g.V(a.L).experiments,"html5_manifestless_captions_fmt3_killswitch")))return d}return null},D2=function(a,b){return a.ua&&null!=a.la||g.V(b).Ma&&null!=a.la&&null!=a.la.g.rawcc},E2=function(a,b,c,d,e,f){A1.call(this,a,b,c,d,e,f);
this.type=1},F2=function(a,b,c,d,e,f){A1.call(this,a,b,c,d,e,f);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.T=0;this.U=this.H=window.NaN;this.ra=null;this.Y=new g.M(this.vK,433,this);g.I(this,this.Y)},G2=function(a){if(!a.T){var b=g.ce("SPAN");
g.Rh(b,B1(a,a.l.Pa));a.o.appendChild(b);b.appendChild(g.de("M"));var c=b.offsetHeight,d=g.ce("BR");b.appendChild(d);b.appendChild(g.de("M"));a.T=b.offsetHeight-c;a.o.removeChild(b)}return a.T},Xka=function(a){if((0,window.isNaN)(a.H)){var b=a.l.Eo;
if(b){var c=g.ce("SPAN");g.re(c,"\u2013".repeat(b));g.Rh(c,B1(a,a.l.Pa));a.o.appendChild(c);a.H=c.offsetWidth;a.o.removeChild(c)}else a.H=0}return a.H},H2=function(a,b,c,d){v2.call(this,d);
c=c||g.or(a).hl||"";c=c.split("_").join("-");this.B=g.qr(a,{hl:c});this.A=b;this.F={};this.o=null},K2=function(a){g.PJ.call(this,a);
this.A=g.V(a);this.o=a.getVideoData();this.na=g.hJ(a);this.L=a;var b=null,c=g.Jq("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.tq(c));this.Z=b;this.C={Pa:{}};this.G={Pa:{}};this.R=[];this.T={};this.ba={};this.N=!1;this.pa="1"==this.o.Ob.cc_auto_caps||"1"==this.A.kc.cc_auto_caps;b="3"==this.A.A&&!!a.app.B&&a.app.B.Lk();this.F=(c=!g.R(this.A.experiments,"web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.o.ua:b;this.da=c&&b&&this.o.ua&&D2(this.o,this.L);c=b=this.l=this.B=
this.H=this.J=this.U=this.ia=null;this.F||(b=new g.Yp(this.Zz,void 0,this),g.I(this,b),c=new g.M(this.NL,2E3,this),g.I(this,c));this.Y=b;this.ga=c;this.ca=new g.Ls(this);g.I(this,this.ca);this.F||this.ca.M(a,"resize",this.Zr);this.ca.M(a,"onPlaybackAudioChange",this.QH);this.ca.M(a,"crn_captions",this.jc,this);this.ca.M(a,"crx_captions",this.we,this);I2(this,J2(this,"display-settings")||{})},L2=function(a){if(1==a.A.fg||1==a.o.fg||"alwayson"==g.dC(a.o,"yt:cc"))return!0;
if(2==a.A.fg){var b=J2(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().zo;return"ON"==c||"on"==g.dC(a.o,"yt:cc")},M2=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.Rl||"FORCED_ON"==c.zo},O2=function(a,b){if(a.B){var c=p2(a.B.l,b||a.pa);
if(a.H&&a.H.g)return a.H.g;for(var d=[a.o.eg,a.A.eg,g.dC(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(s1(c[f])==d[e])return c[f];return a.H&&a.H.Mo?a.H.Mo:(d=c.find(function(a){return a.isDefault}))?d:c[0]||N2(a)}return null},N2=function(a){return a.H&&a.H.Rl},P2=function(a,b){for(var c=a.L.app.B.ha().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},R2=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c,a.N&&Q2(a,"module-enabled",!!b));a.l=b;M2(a)&&(a.l=N2(a));a.load(d)},Yka=function(a,b){var c=g.HL(a.na,!0).height;
if(!c)return null;var d=a.na.Ga();switch(null!=b.params.Zp?b.params.Zp:b.params.kM?2:1<b.l.length?1:0){case 1:return new E2(b,a.C,a.G,c,d.width,d.height);case 2:return new F2(b,a.C,a.G,c,d.width,d.height);default:return new A1(b,a.C,a.G,c,d.width,d.height)}},I2=function(a,b,c){var d=S2.Pa;
a.C={};g.Ka(a.C,S2);a.C.Pa={};g.Ka(a.C.Pa,d);a.G={Pa:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;$1.test(f);e.Pa.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;$1.test(f);e.Pa.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||S2.windowColor;$1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Pa.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.Pa.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.ke?3:d.bold?1:d.ke?2:0);f=f.Pa;switch(e){case 1:f.bold=!0;delete f.ke;break;case 2:delete f.bold;f.ke=!0;break;case 3:f.bold=!0;f.ke=!0;break;default:delete f.bold,delete f.ke}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Pa.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=S2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.Pa.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Pa.fontFamily=f;a.loaded&&a.Zr();c&&Q2(a,"display-settings",b)},U2=function(a,b){if(b&&!a.J){var c=y1({Ui:0,
lang:"en"});a.J=[c,new v1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.vJ(a.g,a.J)}else!b&&a.J&&(T2(a,a.J),a.J=null)},T2=function(a,b){a.g.Fk(b);
(0,g.C)(b,function(a){g.Xa(this.R,a)},a);
a.Y.Lj()},Zka=function(a,b){return a&&g.v(a)&&$1.test(a)?a:b},$ka=function(a,b){return g.wa(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},ala=function(a,b){return g.wa(a)&&!(0,window.isNaN)(a)?g.yd(a,-2,4):b},J2=function(a,b){if(!a.Z)return null;
try{var c=a.Z.get(b)}catch(d){a.Z.remove(b)}return c},Q2=function(a,b,c){if(a.Z)try{a.Z.set(b,c)}catch(d){}};
g.OD.prototype.bi=g.da(10,function(){for(var a=g.Md(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.ie(a[b])});
g.qH.prototype.bi=g.da(9,function(){this.g.bi()});
g.OD.prototype.Lk=g.da(8,function(){return!!this.g.textTracks});
g.qH.prototype.Lk=g.da(7,function(){return this.g.Lk()});
g.OD.prototype.gj=g.da(6,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.qH.prototype.gj=g.da(5,function(a){this.g.gj(a)});
g.uw.prototype.Zl=g.da(3,function(a){return(a=this.mg(a))?a.l:0});
g.Dy.prototype.Zl=g.da(2,function(){return 0});
g.Vu.prototype.J=g.da(1,function(a){return a?this.toString()==a.toString():!1});
var Uka=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Jka=/#(.)(.)(.)/,Ika=/^#(?:[0-9a-f]{3}){1,2}$/i,$1=/^#(?:[0-9a-f]{3}){1,2}$/i;var Kka=["left","right","center","justify"];var S2={windowColor:"#080808",windowOpacity:0,textAlign:2,hf:7,ne:50,Rf:100,Pa:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(v1,g.DD);g.r(w1,g.DD);var x1=0;g.r(A1,g.Q);g.h=A1.prototype;g.h.eG=function(a,b){var c=g.hi(this.element,this.element.parentElement);this.da=a-c.x;this.ia=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.dG=function(a,b){var c=g.li(this.element),d=a-this.da-.02*this.Ha,e=b-this.ia-.02*this.za,f=(d+c.width/2)/this.Z*3;f=Math.floor(g.yd(f,0,2));var k=(e+c.height/2)/this.na*3;k=Math.floor(g.yd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Z;d=100*g.yd(d,0,1);c=(e+k/2*c.height)/this.na;c=100*g.yd(c,0,1);this.F.params.hf=l;this.F.params.Rf=c;this.F.params.ne=d;this.l.hf=l;this.l.Rf=c;this.l.ne=d;this.Yy()};
g.h.cG=function(){g.Rp(this.element,"ytp-dragging")};
g.h.Yy=function(){this.Gh(this.A)};
g.h.Gh=function(a){var b=Math.min(this.qu(),this.Z),c=this.pu();g.Rh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.po(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.ne+2,e=this.l.hf;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.o.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Rf+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Rh(this.element,a)};
g.h.po=function(a){var b;for(b=0;b<a.length&&a[b]==this.A[b];b++);if(this.N||this.A.length>b)b=0,this.N=!1,this.A=[],this.C=[],this.G=[],this.B=null,g.ge(this.o);for(;b<a.length;b++)C1(this,a[b])};
g.h.qu=function(){return 0};
g.h.pu=function(){return 0};D1.prototype.B=function(){};F1.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
F1.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var G1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];I1.prototype.set=function(a){this.g=a};
I1.prototype.get=function(){return this.g};
J1.prototype.clear=function(){this.g=0};
J1.prototype.update=function(){this.g=2==this.g?1:0};
J1.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
K1.prototype.xl=function(a){this.Ld=a.Ld;this.timestamp=a.timestamp};
K1.prototype.reset=function(){this.timestamp=this.Ld=0};
L1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.Ld?a+"_":a+String.fromCharCode(d.Ld)}a+="\n"}return a};
L1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var Oka=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Pka=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Qka=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Rka=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];S1.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.F;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
E1.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};g.r(W1,g.H);W1.prototype.reset=function(){};g.r(X1,W1);X1.prototype.o=function(a){var b=a.firstChild;a=[];this.g||(this.g=y1(this.l),a.push(this.g));b=Array.from(b.childNodes);b=g.p(b);for(var c=b.next();!c.done;c=b.next())Z1(c.value,this.g.id,a);return a};g.r(a2,W1);
a2.prototype.o=function(a){var b=a.firstChild;a=[];this.g||(this.g=y1(),this.l[this.g.id]=this.g,a.push(this.g));for(b=b.firstChild;b;){switch(b.tagName){case "window":var c=b,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||
(f=y1());var k={};f&&(g.Ka(k,f.params),f=f.params.Pa)&&(k.Pa={},g.Ka(k.Pa,f));e.getAttribute("rc")&&(k.Cn=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Eo=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.hf=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ne=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Rf=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Ui=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Ui=0));e.getAttribute("bc")&&(k.Pa||(k.Pa={}),k.Pa.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.Pa||(k.Pa={}),k.Pa.backgroundOpacity=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.Pa||(k.Pa={}),k.Pa.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.kM=(0,window.parseInt)(e.getAttribute("sd"),
10));f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+x1++;c=new w1(c,f,0,e,k)}else c=null}this.l[d]=c;a.push(c);break;case "text":for(d=[],Z1(b,this.g.id,d),d=g.p(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&a.push(c)}b=b.nextSibling}return a};g.r(b2,W1);b2.prototype.reset=function(){this.G={};this.l=this.g=null;this.F=!0};
b2.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ka(l,this.A[m]);m=d2(c,"b");null!=m&&(l.bold=
m);m=d2(c,"i");null!=m&&(l.ke=m);m=d2(c,"u");null!=m&&(l.underline=m);m=e2(c,"et");null!=m&&(l.charEdgeStyle=m);m=e2(c,"of");null!=m&&(l.offset=m);m=f2(c,"bc");null!=m&&(l.background=m);m=f2(c,"ec");null!=m&&(l.Ct=m);m=f2(c,"fc");null!=m&&(l.color=m);m=e2(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=c2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=c2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);c=c2(c,"fo");void 0!=c&&(l.textOpacity=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=
g2(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=h2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=i2(this,d,e,!1);g.I(this,this.g);(d=this.G[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.G[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!d2(d,"a");n=(c2(d,"t")||0)+n;var q=c2(d,"d")||5E3;m||(!this.F&&this.l&&this.l.windowId==
l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=""));var u=m?6:5,x=this.A[d.getAttribute("p")],G=d.childNodes;G.length&&(this.F=null!=d.getAttribute("d"));for(var F=0;F<G.length;F++){var K=G[F];0<F&&(m=!0);var aa=void 0;1==K.nodeType&&(aa=K);if(aa&&"s"==aa.tagName){var pa=aa;K=n;aa=q;var ab=l,yb=m,ke=u,Jh=pa.textContent?pa.textContent:"",Sf=this.A[pa.getAttribute("p")];pa=c2(pa,"t")||0;K=new v1(K+pa,aa-pa,ke,ab,Jh,yb,Sf)}else K=new v1(n,q,u,l,K.textContent||"",m,x);k.push(K);
this.l=K}if(0<k.length)for(k[0].windowId==this.B&&(this.g=i2(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.l.push(k),c.push(k)}e=c}else e=[];return e};g.r(j2,D1);j2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+x1++;c=c/1E3-this.F;d=d/1E3-this.F;a=new w1(c,d-c,5,f,{textAlign:0,hf:0,ne:2.5*b,Rf:5.33*a});e=new v1(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.r(m2,W1);m2.prototype.o=function(a){a=new j2(a,a.byteLength,this.l);if(n2(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=l2(a)*(1E3/45):1==a.version&&(a.A=4294967296*l2(a)+l2(a)),a.C=k2(a);0<a.C;a.C--){var b=k2(a),c=k2(a),d=k2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,wt:c,xt:d,order:b.g.length}))}Nka(this.g,a);return a.o}return[]};
m2.prototype.reset=function(){this.g.clear()};g.r(r2,W1);
r2.prototype.o=function(a,b){for(var c=[],d=a.split(bla),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!dla.test(f)){var l=V2.exec(f);if(l&&4<=l.length){var m=t2(l[1]),n=t2(l[2])-m;m+=k;var q,u=q=void 0,x=void 0,G=void 0,F=l[3];l={textAlign:2};F=g.p(F?F.split(" "):[]);for(var K=F.next();!K.done;K=F.next())if(K=K.value.split(":"),2==K.length){var aa=K[1];switch(K[0]){case "line":K=aa.split(",");K[0].endsWith("%")&&(G=K[0],l.Rf=Number.parseInt(G,10),2==K.length&&(x=K[1].trim()));break;case "position":K=aa.split(",");
u=K[0];l.ne=Number.parseInt(u,10);2==K.length&&(q=K[1].trim());break;case "align":switch(aa){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}G||(l.Rf=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.ne=0;break;case 1:l.ne=100;break;default:l.ne=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(q){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.hf=0>u||8<u?7:u;q=l;f=f.substring(V2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=u2(m,n,5,u),n=new v1(m,n,5,k.id,q,!1,g.jc(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.l.push(n);else for(x=q.split(ela),1==x.length?(q=5,u=u2(m,n,q,u)):(G=q=6,u=Object.assign({Eo:32},u),u=new w1(m,n,G,"_"+x1++,u)),c.push(u),G=m,l=0;l<x.length;l++)F=x[l],0==l%2?(K=g.Up("<html>"+F+"</html>"),K.getElementsByTagName("parsererror").length?
(aa=K.createElement("span"),aa.appendChild(K.createTextNode(F))):aa=K.firstChild,s2(this,G,n-(G-m),q,u,0<l,aa,f,c)):G=t2(F)+k}V2.lastIndex=0}}return c};
var dla=/^NOTE/,bla=/(?:\r\n|\r|\n){2,}/,V2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ela=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(v2,g.H);v2.prototype.trackCount=function(){return p2(this.l,!0).length};
v2.prototype.ld=function(){this.g=null};
v2.prototype.V=function(){g.H.prototype.V.call(this);this.ld()};
v2.prototype.By=function(){return!1};g.r(x2,v2);g.h=x2.prototype;g.h.Up=function(a,b){var c=this.Ij(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.ld();this.o=g.zr(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Vp=function(a,b,c,d){this.A=c;if(d)for(b=g.p(d.captionTracks),c=b.next();!c.done;c=b.next())q2(this.l,c.value);a()};
g.h.Ij=function(a){var b=a.yb(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.qr(b,c)};
g.h.ld=function(){v2.prototype.ld.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.ld();v2.prototype.V.call(this)};y2.prototype.contains=function(a){a=g.jb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
y2.prototype.length=function(){return this.Ua.length/2};g.r(z2,g.H);g.h=z2.prototype;g.h.V=function(){g.H.prototype.V.call(this);this.l&&this.l.cancel()};
g.h.Aw=function(a){var b=this;if(this.G.oi())var c=this.B.M(this.o,"progresssync",function(){b.G.index.Kb()&&(b.reset(),b.g=null,A2(b,b.o.getCurrentTime()),b.B.Ka(c))});
else A2(this,a)};
g.h.reset=function(){this.C=new y2;this.l&&(this.l.cancel(),this.l=null)};
g.h.zv=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Gf(a);!a||this.l||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.xi(a),!g.R(g.V(this.o).experiments,"disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].oa)||B2(this,a),this.g=g.Ma(a.g));this.J.start()};
g.h.qK=function(a){var b=!(this.F?a.response:a.responseText)||400<=a.status;if(!g.R(g.V(this.o).experiments,"disable_captions_redirects_redux")){var c=g.Iy(a);if(c){a=g.ky(this.A,this.N,{});b=this.A;g.gy(b.l,a,c);b.requestId=a.get("req_id");B2(this,this.A);return}}b||null===this.H||(this.F?this.H(a.response,1E3*(this.A.g[0].startTime+t1(this.o))):this.H(a.responseText,1E3*(this.A.g[0].startTime+t1(this.o))));this.l=this.A=null};g.r(C2,v2);g.h=C2.prototype;g.h.Up=function(a,b){this.ld();var c=Wka(this,a.l);if(c&&c.index){var d=c.index.Zl(c.index.ge());g.R(g.V(this.L).experiments,"html5_disable_caption_starttime")||(d-=c.index.gd(c.index.ge()));d*=1E3;var e=g.V(this.L).Ma;this.A=new z2(new g.Ox,this.L,c,function(c,e){b(c,a,e,d)},e||g.iv(c.info),(0,g.A)(function(){this.A&&this.A.reset();
this.g&&this.g.reset();this.B=!0},this))}};
g.h.By=function(){var a=this.B;this.B=!1;return a};
g.h.Vp=function(a){if(g.V(this.L).Ma)q2(this.l,new g.Vu({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})),q2(this.l,new g.Vu({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}));else for(var b in this.o.g){var c=this.o.g[b];if(g.lv(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.R(g.V(this.L).experiments,"html5_manifestless_captions_fmt3_killswitch"))){var d="en",
e="English",f=".en";if(c=c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;q2(this.l,new g.Vu({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.ld=function(){v2.prototype.ld.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Ij=function(){return""};
g.h.V=function(){this.ld();v2.prototype.V.call(this)};g.r(E2,A1);E2.prototype.po=function(a){var b=this.F.l;A1.prototype.po.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ka(d,c.l);g.Ka(d,fla);var e=c.l;var f=d}C1(this,c,d)}};
var fla={Ap:!0};g.r(F2,A1);g.h=F2.prototype;g.h.Yy=function(){g.bq(this.Y)};
g.h.vK=function(){g.Rp(this.element,"ytp-rollup-mode");this.Gh(this.ra,!0)};
g.h.qu=function(){return this.J};
g.h.pu=function(){return this.F.params.Cn*G2(this)};
g.h.Gh=function(a,b){this.ra=a;if(G2(this)){for(var c=0,d=0;d<this.A.length&&c<a.length;d++)this.A[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.A.concat(a.slice(c)));c=this.J;this.J=0;A1.prototype.Gh.call(this,a);d=this.o.offsetWidth+1;this.J=Math.max(Xka(this),c,d);c=this.F.params.Cn*G2(this)-this.o.offsetHeight;c!=this.U&&(b||(0,window.isNaN)(this.U)||(g.J(this.element,"ytp-rollup-mode"),g.aq(this.Y)),g.Rh(this.o,"transform",c?"translateY("+c+"px)":""),this.U=c);A1.prototype.Gh.call(this,a)}else A1.prototype.Gh.call(this,
a)};g.r(H2,v2);g.h=H2.prototype;g.h.Up=function(a,b){var c=this.Ij(a),d=(0,g.A)(function(c){this.o=null;b(c.responseText,a)},this);
this.ld();this.o=g.zr(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Vp=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.Xu&&(b.asrs=1);d=g.qr(d,b);b=(0,g.A)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.p(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),u=m.getAttribute("name"),x=m.getAttribute("kind"),G=m.getAttribute("id"),F="true"==m.getAttribute("lang_default"),
K="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");q2(d,new g.Vu({formats:l,format:c,languageCode:n,languageName:q,name:u,kind:x,id:G,is_servable:!0,is_translateable:K,vss_id:m,is_default:F}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),u=b[e].getAttribute("id"),x="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:q,id:u,
is_default:x},this.F[l.languageCode]=l.languageName,this.C.push(new g.Uu(l))}a()},this);
this.ld();this.o=g.zr(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Ij=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.C,kind:a.B,fmt:a.o};a.g&&(c.tlang=s1(a));return b=g.qr(b,c)};
g.h.ld=function(){v2.prototype.ld.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.ld();v2.prototype.V.call(this)};g.r(K2,g.PJ);g.h=K2.prototype;g.h.V=function(){if(this.F){var a=this.L.app.B;a&&a.bi()}else U2(this,!1);g.PJ.prototype.V.call(this)};
g.h.Vv=function(){return this.F?!this.o.ua:this.da||M2(this)?!0:L2(this)};
g.h.load=function(a){g.PJ.prototype.load.call(this);this.H=this.g.getAudioTrack();if(this.B||a)this.l&&(this.F&&!g.R(this.A.experiments,"disable_native_caption_api")?P2(this,!0):a?this.my(a,this.l):3!=this.g.Da()&&this.B.Up(this.l,(0,g.A)(this.my,this))),this.l&&this.l!=N2(this)?this.g.ma("captionschanged",r1(this.l)):this.g.ma("onCaptionsTrackListChanged");else{var b;D2(this.o,this.L)?b=new C2(this.o.la,this.g):this.o.captionTracks.length?b=new x2(this.o):b=new H2(this.o.sl,this.o.videoId,this.o.eg||
this.A.eg||g.dC(this.o,"yt:cc_default_lang")||this.A.Mb,this.o.rl);this.B=b;g.I(this,this.B);b.Vp((0,g.A)(this.XK,this),!0,this.F?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.F?g.R(this.A.experiments,"disable_native_caption_api")?this.L.app.B.bi():this.l&&P2(this,!1):(this.ga&&g.cq(this.ga),g.yJ(this.g,"captions"),this.R=[],this.B&&this.B.ld(),this.J&&g.vJ(this.g,this.J),this.Zr());g.PJ.prototype.unload.call(this);var a=g.W(this.g.app);a&&a.A&&g.vC(a.A.o);this.g.ma("captionschanged",{})};
g.h.XK=function(){var a;this.N||L2(this)?a=O2(this,this.N):M2(this)&&(a=N2(this));if(this.F||this.da){for(var b=p2(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Wu(e),srclang:s1(e),id:e.toString()};this.da||(f.src=this.B.Ij(e));e==a&&(f["default"]=1);c.push(g.ae("TRACK",f))}this.L.app.B.gj(c);(a=this.L.app.B.ha())&&a.textTracks&&a.textTracks.addEventListener&&!g.R(this.A.experiments,"disable_native_caption_api")&&this.ca.M(a.textTracks,"change",this.YK)}else!this.l&&
a&&R2(this,a),this.g.ma("onCaptionsTrackListChanged"),this.g.ma("onApiChange")};
g.h.YK=function(){for(var a=this.L.app.B.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=p2(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&R2(this,b,!0)};
g.h.vM=function(){g.R(this.A.experiments,"disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.l&&this.F||this.unload()};
g.h.my=function(a,b,c,d){if(a){this.B.By()&&(this.R=[],g.yJ(this.L,"captions"),this.Y.Lj());a=Vka(this.B,a,b,c,d);g.vJ(this.g,a);if(this.N&&!this.da&&this.l!=N2(this)){!this.N||g.Qz(this.A)||g.Wz(this.A)||(g.cq(this.ga),a=y1({hf:0,ne:5,Rf:5,Cn:2,textAlign:0,Ui:0,lang:"en"}),this.U=[a],b=["Click "," for settings"],this.ia||(c=new g.yu(g.mO()),g.I(this,c),this.ia=c.element),c=a.end-a.start,(d=g.Wu(this.l))&&this.U.push(new v1(a.start,c,0,a.id,d)),this.U.push(new v1(a.start,c,0,a.id,b[0]),new v1(a.start,
c,0,a.id,this.ia,!0),new v1(a.start,c,0,a.id,b[1],!0)),g.vJ(this.g,this.U),g.aq(this.ga));if(this.N||g.Qz(this.A))Q2(this,"module-enabled",!0),this.H&&(this.H.g=this.l);(a=g.W(this.g.app))&&a.A&&g.vC(a.A.o)}this.N=!1}};
g.h.jc=function(a){this.R.push(a);this.Y.Lj()};
g.h.we=function(a){g.Xa(this.R,a);var b=D2(this.o,this.L)&&this.A.Ma;!g.R(this.A.experiments,"disable_remove_displayed_close_caption_cue")&&b&&this.g.Fk([a]);this.Y.Lj()};
g.h.HL=function(a){if(a instanceof w1){var b=this.T[a.id];b&&b.F!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=Yka(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.ba[b]||(this.ba[b]=[]),this.ba[b].push(a)};
g.h.NL=function(){T2(this,this.U);this.U=null};
g.h.Zz=function(){this.Y.stop();g.kc(this.ba);this.R.sort(g.FD);var a=this.R;if(this.J){var b=(0,g.le)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.HL,this);g.Xb(this.T,function(a,b){this.ba[b]?(a.element.parentNode||g.CJ(this.g,a.element,4),a.Gh(this.ba[b])):(a.dispose(),delete this.T[b])},this)};
g.h.Xy=function(){I2(this,{},!0)};
g.h.gp=function(){var a=S2.Pa;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.ke?3:a.bold?1:a.ke?2:0,textOpacity:a.textOpacity,windowColor:S2.windowColor,windowOpacity:S2.windowOpacity};var b=J2(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.gs=function(a,b){var c={};g.Ka(c,J2(this,"display-settings"));g.Ka(c,a);I2(this,c,b);this.g.P("captionssettingschanged")};
g.h.Zr=function(){!this.F&&this.loaded&&(g.Xb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.Zz())};
g.h.iq=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.yd(b,-2,4);this.gs({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&R2(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.nb&&Q2(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Da(b))break;if(g.jc(b)){R2(this,null,!0);break}var d;c=p2(this.B.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.A!=b.languageName||(d=b.translationLanguage?
Hka(f,b.translationLanguage):f)}!d||d==this.l&&this.loaded||R2(this,d,!0)}else return this.loaded&&this.l&&this.l!=N2(this)?r1(this.l):{};return"";case "tracklist":return this.B?(0,g.E)(p2(this.B.l,!(!b||!b.includeAsr)),function(a){return r1(a)}):[];
case "translationLanguages":return this.B?this.B.C:[];case "displaySettings":d=this.gp();if(g.Qz(this.A)&&b&&g.Da(b))if(b.reset)this.Xy();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Zka(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=$ka(b[c],d[c]);break;case "charEdgeStyle":var k=g.lX[b[c]];f[c]=g.wa(k)?k:d[c];break;case "fontSizeIncrement":f[c]=ala(b[c],d[c]);break;case "fontFamilyOption":k=g.kX[b[c]];f.fontFamily=
g.wa(k)?k:d[c];break;case "fontStyle":k=g.mX[b[c]],f[c]=g.wa(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.gs(f,!0);d=this.gp()}d.fontFamilyOption=g.$ha[d.fontFamily];d.charEdgeStyle=g.aia[d.charEdgeStyle];d.fontStyle=g.bia[d.fontStyle];return d;case "sampleSubtitles":this.F||void 0==b||U2(this,!!b);break;case "xmlTrack":b&&this.A.nb&&(this.F||R2(this,new g.Vu({languageName:b.name}),!1,b.xml))}};
g.h.oE=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.nb&&a.push("stickyLoading","xmlTrack");return a};
g.h.Jj=function(){var a=this.l;return a?{cc:a.F}:{}};
g.h.Oz=function(){this.loaded&&this.l&&this.l!=N2(this)?(Q2(this,"module-enabled",!1),this.unload(),M2(this,!0)&&R2(this,N2(this),!1)):R2(this,this.l==N2(this)?O2(this,!0):this.l,!0)};
g.h.QH=function(){var a=this.l==N2(this);M2(this,a)?R2(this,this.g.getAudioTrack().Rl,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.Vv()&&(a?R2(this,O2(this),!1):this.load()))};g.tQ.captions=K2;})(_yt_player);
