(function(g){var window=this;var W2=function(a,b,c,d){var e=b.vb();g.L(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.sc(c,d?d:"mqdefault.jpg");var k=b instanceof g.FB&&b.lengthSeconds?g.EO(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.GD(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.FB?b.ua:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.hj||g.du("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,
url:b.Kj(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.ID&&(c.playlist_length=b.getLength());a.update(c)},X2=function(a,b){g.Eu.call(this,{D:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},Y2=function(a){g.Q.call(this,{D:"div",
I:"ytp-upnext",O:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",O:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",O:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",I:"ytp-svg-autoplay-circle",
O:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",O:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",O:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});this.A=null;var b=
this.g["ytp-upnext-cancel"];this.A=new g.Q({D:"button",X:["ytp-upnext-cancel-button","ytp-button"],O:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.I(this,this.A);this.A.ea("click",this.VH,this);this.A.aa(b);this.l=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.C=this.o=this.B=null;this.G=new g.M(this.wl,5E3,this);g.I(this,this.G);this.H=0;this.M(this.g["ytp-upnext-autoplay-icon"],"click",this.OJ);this.Cx();this.M(a,"autonavvisibility",this.Cx);this.M(a,"mdxnowautoplaying",this.eJ);
this.M(a,"mdxautoplaycanceled",this.fJ);this.M(a,"mdxautoplayupnext",this.dA);3==this.l.Da()&&(a=(a=g.iJ(g.bJ(this.l)))?a.uC():null)&&this.dA(a)},Z2=function(a,b){a.B=b;
W2(a,b,g.V(a.l),"hqdefault.jpg")},$2=function(a,b){if(!a.o){g.bt("a11y-announce","Up Next "+a.B.title);
a.H=g.P();a.o=new g.M((0,g.A)(a.oo,a,b),25);a.oo(b);var c=b||g.S(g.V(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.Rp(a.element,"ytp-upnext-autoplay-paused")},b3=function(a){a3(a);
a.H=g.P();a.oo();g.J(a.element,"ytp-upnext-autoplay-paused")},a3=function(a){a.o&&(a.o.dispose(),a.o=null)},c3=function(a,b){b=void 0===b?!1:b;
var c=g.V(a.l);if(g.R(c.experiments,"autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.B.vb(),a.wl(),a.C=new window.Notification("Up Next",{body:d.title,icon:d.sc(c)}),a.F=a.M(a.C,"click",a.FJ),a.G.start())}a3(a);a.l.Ei(!1,b)},d3=function(a){X2.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.Q({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",O:{src:b.profilePicture}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.I(this,this.o);this.o.aa(this.element);this.A=new g.UT("Subscribe",null,"Unsubscribe",null,!0,!1,b.Yi,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.A);this.A.aa(this.o.g["html5-subscribe-button-container"]);this.hide()},e3=
function(a){var b=g.V(a),c=g.rv||g.Uh?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{D:"a",X:e,O:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",O:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",O:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.Ls(this);g.I(this,this.A);this.ea("click",this.F);this.ea("keypress",this.G);this.A.M(a,"videodatachange",this.C);g.V(a).B&&g.KK(a.app.U,this.element,this);this.C()},f3=function(a){g.GJ(a.l,a.element);
var b=a.o.vb().videoId,c=a.o.getPlaylistId();g.ZV(a.l.app,b,a.o.jd,c,void 0,void 0,void 0)},g3=function(a){X2.call(this,a,"videowall-endscreen");
this.J=a;this.F=0;this.A=[];this.G=this.C=this.B=null;this.H=this.T=!1;this.ca=new g.Ls(this);g.I(this,this.ca);this.N=new g.M(g.Ja(g.J,this.element,"ytp-show-tiles"),0);g.I(this,this.N);var b=new g.Q({D:"button",X:["ytp-button","ytp-endscreen-previous"],O:{"aria-label":"Previous"},K:[g.WN()]});g.I(this,b);b.aa(this.element);b.ea("click",this.WF,this);this.R=new g.yu({D:"div",I:"ytp-endscreen-content"});g.I(this,this.R);this.R.aa(this.element);b=new g.Q({D:"button",X:["ytp-button","ytp-endscreen-next"],
O:{"aria-label":"Next"},K:[g.XN()]});g.I(this,b);b.aa(this.element);b.ea("click",this.VF,this);this.o=new Y2(a);g.I(this,this.o);g.CJ(this.l,this.o.element,4);this.hide()},h3=function(a){return g.DJ(a.l)&&a.mt()&&!a.G},i3=function(a,b){return(0,g.E)(b.suggestions,function(b){b=g.BQ(g.V(a.J),b);
g.I(a,b);return b})},j3=function(a){var b=a.Aq();
b!=a.T&&(a.T=b,a.l.P("autonavvisibility"))},l3=function(a){g.PJ.call(this,a);
this.l=null;this.o=new g.Ls(this);g.I(this,this.o);this.A=g.V(a);k3(a)?this.l=new g3(this.g):this.A.Ha?this.l=new d3(this.g):this.l=new X2(this.g);g.I(this,this.l);g.CJ(this.g,this.l.element,4);this.Wy();this.o.M(a,"videodatachange",this.Wy,this);this.o.M(a,"crn_endscreen",this.jc,this);this.o.M(a,"crx_endscreen",this.we,this)},k3=function(a){a=g.V(a);
return a.Jc&&!a.Ha};
g.r(X2,g.Eu);X2.prototype.create=function(){this.created=!0};
X2.prototype.zq=function(){this.created=!1};
X2.prototype.mt=function(){return!1};
X2.prototype.Aq=function(){return!1};g.r(Y2,g.Q);g.h=Y2.prototype;g.h.wl=function(){this.C&&(this.G.stop(),this.Ka(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.Cx=function(){g.Du(this,g.cJ(this.l))};
g.h.FJ=function(){window.focus();this.wl()};
g.h.hide=function(){g.Q.prototype.hide.call(this)};
g.h.oo=function(a){a=a||g.S(g.V(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Da()?c3(this,!0):this.o&&this.o.start()};
g.h.OJ=function(a){!g.qe(this.A.element,g.As(a))&&g.lQ(a,this.l)&&c3(this)};
g.h.VH=function(){g.eJ(this.l,!0)};
g.h.eJ=function(a){this.l.Da();this.show();$2(this,a)};
g.h.dA=function(a){this.l.Da();this.B&&this.B.vb().videoId==a.vb().videoId||Z2(this,a)};
g.h.fJ=function(){this.l.Da();a3(this);this.hide()};
g.h.V=function(){a3(this);this.wl();g.Q.prototype.V.call(this)};g.r(d3,X2);g.r(e3,g.Q);e3.prototype.F=function(a){g.lQ(a,this.l,this.B,this.o.jd||void 0)&&f3(this)};
e3.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.Fs(a)||(f3(this),g.Es(a))}};
e3.prototype.C=function(){var a=this.l.getVideoData(),b=g.V(this.l);this.B=a.isDni?!1:b.g};g.r(g3,X2);g.h=g3.prototype;g.h.create=function(){X2.prototype.create.call(this);var a=this.l.getVideoData();a&&(this.B=i3(this,a),this.C=a);this.Jf();this.ca.M(this.l,"appresize",this.Jf);this.ca.M(this.l,"onVideoAreaChange",this.Jf);this.ca.M(this.l,"videodatachange",this.XF);this.ca.M(this.l,"autonavchange",this.ww);this.ca.M(this.l,"autonavcancel",this.UF);this.ca.M(this.element,"transitionend",this.ZK)};
g.h.zq=function(){g.Ns(this.ca);g.mf(this.A);this.A=[];this.B=null;X2.prototype.zq.call(this);g.Rp(this.element,"ytp-show-tiles");this.N.stop()};
g.h.mt=function(){return 1!=this.C.autonavState};
g.h.show=function(){X2.prototype.show.call(this);g.Rp(this.element,"ytp-show-tiles");g.V(this.l).o?g.bq(this.N):this.N.start();(this.H||this.G&&this.G!=this.C.clientPlaybackNonce)&&g.eJ(this.l,!1);h3(this)?(j3(this),2==this.C.autonavState?g.R(g.V(this.l).experiments,"fast_autonav_in_background")&&3==this.l.Hf()?c3(this.o,!0):$2(this.o):3==this.C.autonavState&&b3(this.o)):(g.eJ(this.l,!0),j3(this))};
g.h.hide=function(){X2.prototype.hide.call(this);b3(this.o);j3(this)};
g.h.ZK=function(a){g.As(a)==this.element&&this.Jf()};
g.h.Jf=function(){if(this.B&&this.B.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.sJ(this.J,!0),b=g.Su(this.J);b&&(b=b.Cc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.B.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,u=e/2,x=b<=f-2&&n>=u*m,G=e<=k-2&&n>=q*m;if((q+1)/u*d/c>c/(q/(u+1)*d)&&G)n-=q*m,e+=2;else if(x)n-=u*m,b+=2;else if(G)n-=q*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.yd(a.width/m||1,1,1.21);n*=g.yd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.R.element;g.ji(a,m,n);g.Rh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});Z2(this.o,this.B[0]);g.L(this.element,"ytp-endscreen-takeover",h3(this));j3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,u=0,d&&f>=b-2&&k>=e-2?u=1:0==k%2&&0==f%2&&(2>k&&2>
f?0==k&&0==f&&(u=2):u=2),q=g.zd(q+this.F,l),0!=u){x=this.A[c];x||(x=new e3(this.l),this.A[c]=x,a.appendChild(x.element));G=Math.floor(n*k/e);var F=Math.floor(m*f/b),K=Math.floor(n*(k+u)/e)-G-4,aa=Math.floor(m*(f+u)/b)-F-4;g.Zh(x.element,F,G);g.ji(x.element,aa,K);g.Rh(x.element,"transitionDelay",(k+f)/20+"s");g.L(x.element,"ytp-videowall-still-mini",1==u);g.L(x.element,"ytp-videowall-still-large",2<u);u=x;q=this.B[q];u.o!=q&&(u.o=q,W2(u,q,g.V(u.l),g.Pp(u.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),q=(q=q.jd)&&q.itct)&&(x=u.l,g.V(x).B&&g.LK(x.app.U,u.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.ie(e.element),g.lf(e);this.A.length=c}};
g.h.XF=function(){var a=this.l.getVideoData();this.C!=a&&(this.F=0,this.B=i3(this,a),this.C=a,this.Jf())};
g.h.VF=function(){this.F+=this.A.length;this.Jf()};
g.h.WF=function(){this.F-=this.A.length;this.Jf()};
g.h.xD=function(){return!!this.o.o};
g.h.ww=function(a){1==a?(this.H=!1,this.G=this.C.clientPlaybackNonce,a3(this.o),this.Ja()&&this.Jf()):(this.H=!0,this.Ja()&&h3(this)&&(2==a?$2(this.o):3==a&&b3(this.o)))};
g.h.UF=function(a){if(a){for(a=0;a<this.A.length;a++)g.HJ(this.J,this.A[a].element,!0);this.ww(1)}else this.G=null,this.H=!1;this.Jf()};
g.h.Aq=function(){return this.Ja()&&h3(this)};g.r(l3,g.PJ);g.h=l3.prototype;g.h.Uv=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!k3(this.g)||b;a=g.gC(a,"ypc_module");var c=g.pV(this.g.app);return b&&!a&&!c};
g.h.Tv=function(){return this.l.Aq()};
g.h.tD=function(){return this.Tv()?this.l.xD():!1};
g.h.V=function(){g.yJ(this.g,"endscreen");g.PJ.prototype.V.call(this)};
g.h.load=function(){g.PJ.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.PJ.prototype.unload.call(this);this.l.hide();this.l.zq()};
g.h.jc=function(a){this.Uv()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.we=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Wy=function(){g.yJ(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.DD(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.DD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.vJ(this.g,[a,b])};g.tQ.endscreen=l3;})(_yt_player);
